[package]
name = "test_gen"
description = "Contains all of Broc's code generation tests."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[[test]]
name = "test_gen"
path = "src/tests.rs"

[build-dependencies]
broc_bitcode = { path = "../builtins/bitcode" }
broc_command_utils = { path = "../../utils/command" }
wasi_libc_sys = { path = "../../wasi-libc-sys" }

tempfile.workspace = true

[dev-dependencies]
broc_bitcode = { path = "../builtins/bitcode" }
broc_build = { path = "../build", features = ["target-aarch64", "target-x86_64", "target-wasm32"] }
broc_builtins = { path = "../builtins" }
broc_can = { path = "../can" }
broc_collections = { path = "../collections" }
broc_command_utils = { path = "../../utils/command" }
broc_constrain = { path = "../constrain" }
broc_debug_flags = { path = "../debug_flags" }
broc_error_macros = { path = "../../error_macros" }
broc_gen_dev = { path = "../gen_dev" }
broc_gen_llvm = { path = "../gen_llvm" }
broc_gen_wasm = { path = "../gen_wasm" }
broc_load = { path = "../load" }
broc_module = { path = "../module" }
broc_mono = { path = "../mono" }
broc_packaging = { path = "../../packaging" }
broc_parse = { path = "../parse" }
broc_problem = { path = "../problem" }
broc_region = { path = "../region" }
broc_reporting = { path = "../../reporting" }
broc_solve = { path = "../solve" }
broc_std = { path = "../../broc_std" }
broc_target = { path = "../broc_target" }
broc_types = { path = "../types" }
broc_unify = { path = "../unify" }
broc_wasm_interp = { path = "../../wasm_interp" }
broc_wasm_module = { path = "../../wasm_module" }

bumpalo.workspace = true
criterion.workspace = true
indoc.workspace = true
inkwell.workspace = true
lazy_static.workspace = true
libc.workspace = true
libloading.workspace = true
target-lexicon.workspace = true
tempfile.workspace = true


[features]
default = ["gen-llvm"]
gen-dev = []
gen-llvm = []
gen-llvm-wasm = ["gen-llvm"]
gen-wasm = []

[[bench]]
name = "list_map"
harness = false

[[bench]]
name = "quicksort"
harness = false

[package.metadata.cargo-udeps.ignore]
development = ["broc_wasm_interp"]
