[package]
name = "broc_types"
description = "Various representations and utilities for dealing with types in the Broc compiler."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
broc_collections = { path = "../collections" }
broc_debug_flags = { path = "../debug_flags" }
broc_error_macros = { path = "../../error_macros" }
broc_module = { path = "../module" }
broc_region = { path = "../region" }
broc_serialize = { path = "../serialize" }

ven_pretty = { path = "../../vendor/pretty" }

bumpalo.workspace = true
static_assertions.workspace = true
