[package]
name = "broc_parse"
description = "Implements the Broc parser, which transforms a textual representation of a Broc program to an AST."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
"parse_debug_trace" = []

[dependencies]
broc_collections = { path = "../collections" }
broc_module = { path = "../module" }
broc_region = { path = "../region" }

bumpalo.workspace = true
encode_unicode.workspace = true

[dev-dependencies]
criterion.workspace = true
indoc.workspace = true
pretty_assertions.workspace = true
proptest.workspace = true
quickcheck.workspace = true
quickcheck_macros.workspace = true

[[bench]]
harness = false
name = "bench_parse"
