[package]
name = "host"
authors = ["The Broc Contributors"]
edition = "2021"
license = "UPL-1.0"
version = "0.0.1"

links = "app"

[lib]
name = "host"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib"]

[[bin]]
name = "host"
path = "src/main.rs"

[dependencies]
backtrace = "0.3"
libc = "0.2"
reqwest = { version = "0.11.11", default-features = false, features = ["blocking", "rustls-tls"] }
broc_std = { path = "../../../crates/broc_std" }

[workspace]
