[package]
name = "broc_load"
description = "Used to load a .broc file and coordinate the compiler pipeline, including parsing, type checking, and code generation."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
broc_can = { path = "../can" }
broc_collections = { path = "../collections" }
broc_load_internal = { path = "../load_internal" }
broc_module = { path = "../module" }
broc_packaging = { path = "../../packaging" }
broc_reporting = { path = "../../reporting" }
broc_target = { path = "../broc_target" }
broc_types = { path = "../types" }

bumpalo.workspace = true

[build-dependencies]
broc_builtins = { path = "../builtins" }
broc_can = { path = "../can" }
broc_module = { path = "../module" }
broc_packaging = { path = "../../packaging" }
broc_reporting = { path = "../../reporting" }
broc_target = { path = "../broc_target" }

bumpalo.workspace = true

[target.'cfg(not(windows))'.build-dependencies]
broc_load_internal = { path = "../load_internal" }
