[package]
name = "host"
authors = ["The Broc Contributors"]
edition = "2021"
license = "UPL-1.0"
links = "app"
version = "0.0.1"

[lib]
name = "host"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib"]

[[bin]]
name = "host"
path = "src/main.rs"

[dependencies]
libc = "0.2"
broc_std = { path = "../../../crates/broc_std" }

[workspace]
