[package]
name = "host"
authors = ["The Broc Contributors"]
edition = "2021"
license = "UPL-1.0"
version = "0.0.1"

links = "app"

[lib]
name = "host"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib"]

[[bin]]
name = "host"
path = "src/main.rs"

[dependencies]
libc = "0.2"
syntect = "5.0"
broc_highlight = { path = "../../../crates/highlight" }
broc_std = { path = "../../../crates/broc_std" }


# Default features include building a binary that we don't need
pulldown-cmark = { version = "0.9.2", default-features = false }

[workspace]
