[package]
name = "broc_unify"
description = "Implements Broc's unification algorithm, the heartstone of Broc's type inference."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
bitflags.workspace = true

[dependencies.broc_collections]
path = "../collections"

[dependencies.broc_error_macros]
path = "../../error_macros"

[dependencies.broc_module]
path = "../module"

[dependencies.broc_types]
path = "../types"

[dependencies.broc_debug_flags]
path = "../debug_flags"

[dependencies.broc_tracing]
path = "../../tracing"
