[package]
name = "uitest"
description = "Integration tests for the solver."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[[test]]
name = "uitest"
path = "src/uitest.rs"
harness = false

[dev-dependencies]
broc_builtins = { path = "../builtins" }
broc_collections = { path = "../collections" }
broc_derive = { path = "../derive", features = ["debug-derived-symbols"] }
broc_load = { path = "../load" }
broc_packaging = { path = "../../packaging" }
broc_module = { path = "../module", features = ["debug-symbols"] }
broc_mono = { path = "../mono" }
broc_parse = { path = "../parse" }
broc_problem = { path = "../problem" }
broc_reporting = { path = "../../reporting" }
broc_solve = { path = "../solve" }
broc_target = { path = "../broc_target" }
test_solve_helpers = { path = "../test_solve_helpers" }

bumpalo.workspace = true
indoc.workspace = true
insta.workspace = true
lazy_static.workspace = true
pretty_assertions.workspace = true
regex.workspace = true
tempfile.workspace = true
libtest-mimic.workspace = true
