[package]
name = "test_derive"
description = "Tests Broc's auto-derivers."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[[test]]
name = "test_derive"
path = "src/tests.rs"

[dev-dependencies]
broc_builtins = { path = "../builtins" }
broc_can = { path = "../can" }
broc_collections = { path = "../collections" }
broc_constrain = { path = "../constrain" }
broc_debug_flags = { path = "../debug_flags" }
broc_derive = { path = "../derive", features = ["debug-derived-symbols", "open-extension-vars"] }
broc_derive_key = { path = "../derive_key" }
broc_load_internal = { path = "../load_internal" }
broc_module = { path = "../module" }
broc_packaging = { path = "../../packaging" }
broc_region = { path = "../region" }
broc_reporting = { path = "../../reporting" }
broc_solve = { path = "../solve" }
broc_target = { path = "../broc_target" }
broc_types = { path = "../types" }

ven_pretty = { path = "../../vendor/pretty" }

bumpalo.workspace = true
insta.workspace = true
