[package]
name = "host"
version = "0.0.1"
authors = ["The Broc Contributors"]
license = "UPL-1.0"
edition = "2021"
links = "app"

[lib]
name = "host"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib"]

[[bin]]
name = "host"
path = "src/main.rs"

[dependencies]
broc_std = { path = "../../../crates/broc_std" }
libc = "0.2"

[workspace]
