[package]
name = "broc_solve_problem"
description = "Provides types to describe problems that can occur during solving."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
broc_can = { path = "../can" }
broc_collections = { path = "../collections" }
broc_exhaustive = { path = "../exhaustive" }
broc_module = { path = "../module" }
broc_problem = { path = "../problem" }
broc_region = { path = "../region" }
broc_types = { path = "../types" }
