[package]
name = "test_mono"
description = "Tests Broc's generation of the mono intermediate representation."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[[test]]
name = "test_mono"
path = "src/tests.rs"

[dev-dependencies]
broc_builtins = { path = "../builtins" }
broc_can = { path = "../can" }
broc_collections = { path = "../collections" }
broc_load = { path = "../load" }
broc_module = { path = "../module", features = ["debug-symbols"] }
broc_mono = { path = "../mono" }
broc_packaging = { path = "../../packaging" }
broc_reporting = { path = "../../reporting" }
broc_target = { path = "../broc_target" }
broc_tracing = { path = "../../tracing" }

test_mono_macros = { path = "../test_mono_macros" }

bumpalo.workspace = true
indoc.workspace = true
