[package]
name = "broc_module"
description = "Implements data structures used for efficiently representing unique modules and identifiers in Broc programs."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
broc_collections = { path = "../collections" }
broc_error_macros = { path = "../../error_macros" }
broc_ident = { path = "../ident" }
broc_region = { path = "../region" }

bumpalo.workspace = true
snafu.workspace = true
static_assertions.workspace = true

[features]
debug-symbols = []
default = []
