[package]
name = "broc_problem"
description = "Provides types to describe problems that can occur when compiling Broc code."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
broc_collections = { path = "../collections" }
broc_module = { path = "../module" }
broc_parse = { path = "../parse" }
broc_region = { path = "../region" }
broc_types = { path = "../types" }
