[package]
name = "test_syntax"
description = "Tests for the parse + fmt crates."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
"parse_debug_trace" = ["broc_parse/parse_debug_trace"]

[dependencies]
bumpalo.workspace = true
broc_collections = { path = "../collections" }
broc_fmt = { path = "../fmt" }
broc_module = { path = "../module" }
broc_parse = { path = "../parse" }
broc_region = { path = "../region" }
broc_test_utils = { path = "../../test_utils" }

[dev-dependencies]
indoc.workspace = true
pretty_assertions.workspace = true
walkdir.workspace = true
