[package]
name = "test_solve_helpers"
description = "Utilities for testing the solver. This should eventually made into the broc_solve crate, but currently, solve tests have multiple harnesses."

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
broc_can = { path = "../can" }
broc_derive = { path = "../derive" }
broc_load = { path = "../load" }
broc_module = { path = "../module" }
broc_packaging = { path = "../../packaging" }
broc_problem = { path = "../problem" }
broc_region = { path = "../region" }
broc_reporting = { path = "../../reporting" }
broc_solve = { path = "../solve" }
broc_late_solve = { path = "../late_solve" }
broc_solve_problem = { path = "../solve_problem" }
broc_target = { path = "../broc_target" }
broc_types = { path = "../types" }

bumpalo.workspace = true
indoc.workspace = true
insta.workspace = true
lazy_static.workspace = true
pretty_assertions.workspace = true
regex.workspace = true
tempfile.workspace = true
